// <auto-generated />
using System;
using Hotel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20200201145109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel.Klient", b =>
                {
                    b.Property<int>("Id_Klient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Klient");

                    b.ToTable("Klient");
                });

            modelBuilder.Entity("Hotel.Models.Standard", b =>
                {
                    b.Property<int>("StandardPokoju")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CenaStandardu")
                        .HasColumnType("real");

                    b.HasKey("StandardPokoju");

                    b.ToTable("Standard");
                });

            modelBuilder.Entity("Hotel.Pokoj", b =>
                {
                    b.Property<int>("Nr_Pokoju")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Liczba_miejsc")
                        .HasColumnType("int");

                    b.Property<int>("Standard_pokoju")
                        .HasColumnType("int");

                    b.Property<bool>("Wolny")
                        .HasColumnType("bit");

                    b.HasKey("Nr_Pokoju");

                    b.ToTable("Pokoj");
                });

            modelBuilder.Entity("Hotel.Rezerwacja", b =>
                {
                    b.Property<int>("Id_Rezerwacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data_Rozpoczecia_Rezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Zakonczenia_Rezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_klient")
                        .HasColumnType("int");

                    b.Property<int>("nr_pokoju")
                        .HasColumnType("int");

                    b.HasKey("Id_Rezerwacji");

                    b.ToTable("Rezerwacja");
                });
#pragma warning restore 612, 618
        }
    }
}
